name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/bun.lockb" ]; then
            echo "manager=bun" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Bun
        if: steps.detect-package-manager.outputs.manager == 'bun'
        uses: oven-sh/setup-bun@v1

      - name: Setup Node
        if: steps.detect-package-manager.outputs.manager != 'bun'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            node_modules
            bun.lockb
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb', '**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies (bun)
        if: steps.detect-package-manager.outputs.manager == 'bun'
        run: bun install

      - name: Install dependencies (npm/yarn)
        if: steps.detect-package-manager.outputs.manager != 'bun'
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            yarn install
          else
            npm ci
          fi

      - name: Build with Next.js (bun)
        if: steps.detect-package-manager.outputs.manager == 'bun'
        run: bun run build

      - name: Build with Next.js (npm/yarn)
        if: steps.detect-package-manager.outputs.manager != 'bun'
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            yarn next build
          else
            npx next build
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4